######################################
# CONFIGURAÇÃO DO OFELIA SCHEDULER   #
######################################

[job-local "start_automation_maestro"]
schedule = "30 4 * * *"
command = "docker ps -a --format \"{{.Names}}\" | grep atlas_automation_maestro | xargs -n1 docker start || true"

[job-local "stop_automation_maestro"]
schedule = "30 13 * * *"
command = "docker ps -q --filter \"name=atlas_automation_maestro\" | xargs -n1 docker stop || true"

[job-local "start_service_soc_modelo_dois"]
schedule = "0 5 * * *"
command = "docker ps -a --format \"{{.Names}}\" | grep atlas_service_soc_modelo_dois | xargs -n1 docker start || true"

[job-local "stop_service_soc_modelo_dois"]
schedule = "0 13 * * *"
command = "docker ps -q --filter \"name=atlas_service_soc_modelo_dois\" | xargs -n1 docker stop || true"

[job-local "start_rpa_autorizador"]
schedule = "0 8 * * *"
command = "docker ps -a --format \"{{.Names}}\" | grep atlas_rpa_autorizador | xargs -n1 docker start || true"

[job-local "stop_rpa_autorizador_noon"]
schedule = "0 12 * * *"
command = "docker ps -q --filter \"name=atlas_rpa_autorizador\" | xargs -n1 docker stop || true"

[job-local "stop_rpa_autorizador_13h"]
schedule = "0 13 * * *"
command = "docker ps -q --filter \"name=atlas_rpa_autorizador\" | xargs -n1 docker stop || true"
